apiVersion: v1
kind: Namespace
metadata:
  name: tomcat-ps
  labels:
    team: prod-team
---
apiVersion: v1
kind: Pod
metadata:
  name: tomcatapp
  namespace: tomcat-ps
  labels:
    app: tomcatapp
spec:
  containers:
  - name: tomcat
    image: tomcat:latest  # image
    resources:
      limits:
        cpu: 100m
      requests:
        cpu: 50m
    ports:
    - containerPort: 8080
    lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - |
                   cp -R  /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/
---
apiVersion: v1
kind: Service
metadata:
  name: tomcatappsvc
  namespace: tomcat-ps
spec:
  type: NodePort
  selector:
    app: tomcatapp
  ports:
  - port: 80
    targetPort: 8080
